theme: minima
title: Gente con internet y Github
author: Sergio Basilio
email: s3rgio.basilio@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Haremos lo que hace la gente con internet y que está aprendiendo a usar github.
# social links
twitter_username: Sesebasi # DO NOT include the @ character, or else the build will fail!
github_username:  Sesebasi # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
